### ISSUE TITLE
Retry on json fail

### ISSUE THREAD

**Issue by Azarattum** [truework/gretchen#20]
Is there a build-in way to retry the request when json parsing fails? Since it still returns code 200 it cannot be done with ```retry.codes```.

**Comment by Azarattum** [comment]
The current workaround, that I use is:
```TypeScript
const use = () => gretch(url).json();

let res = await use();
if (res.error?.type === "invalid-json") {
	await sleep(6);
	res = await use();
}
```
It archives the desired effect, but not very elegant. It would be nice to have a native solution in ```gretch``` itself.

**Comment by estrattonbailey** [comment]
Hey @Azarattum, sorry for the delay. Interesting use case. What's causing this on your end?

I would typically think a parsing error would be a case where we'd want to fail entirely, since it's usually an issue with the response sent from the server i.e. a JSON endpoint failing with 500 and returning something that's not JSON.

If the endpoint you're using is flaky, you can also try using `.flush()` or `.text()` to resolve the request and only optionally parse the body once you've determined that it's safe to do so.

**Comment by Azarattum** [comment]
Hello. I'm working with quite weird external API which does not return a proper HTTP error code, but a error message in plain text. Obviously, JSON parsing fails there. I just want to retry the request, since that's what gives me the desired data from the API.

I just thought, it wouldn't heart the library to add such an option. And may cover these weird use-cases. After all, *invalid-json* is still an error, so it would be nice to be able to specify a retry on it.

**Comment by estrattonbailey** [comment]
Yeah that sounds like a real headache 😛 I've been there, I understand how frustrating that can be 😕

Retrying is really just to ensure we get a response back in the case of network failures or a proper error code. I think it's a little out of scope for this library to retry parsing of a response body. That really should be the responsibility of the creators of the API.

So in the case of bad API design like you're unfortunately having to deal with, I think it's better to keep this in user-land and handle it on a case-by-case basis like you have been doing.
